# Generated by Django 4.2.13 on 2024-08-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('mode_of_contact', models.CharField(choices=[('email', 'E-Mail'), ('phone', 'Phone')], default='email', max_length=10, verbose_name='Contact by')),
                ('question_type', models.CharField(choices=[('dividends', 'Dividends'), ('investment_strategies', 'Investment Strategies'), ('stock_analysis', 'Stock Analysis'), ('portfolio_management', 'Portfolio Management'), ('taxation', 'Taxation'), ('market_news', 'Market News'), ('blog_content', 'Blog Content'), ('technical_support', 'Technical Support'), ('other', 'Others')], default='dividends', max_length=50, verbose_name='How can we help you?')),
                ('contactmessage', models.TextField(max_length=3000, verbose_name='Message')),
            ],
        ),
    ]
