# Generated by Django 4.2.13 on 2024-08-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutpage_comprehensive_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='about_image',
        ),
    ]
